### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'pdf2htmlEX'

### ISSUE THREAD

**Issue by tiamjiakun** [gabriel-batistuta/pypdf2htmlEX#3]
<img width="1118" alt="iShot_2024-08-01_11 32 27" src="https://github.com/user-attachments/assets/d234d1ce-c3df-4a1b-9007-71edffca7e3f">

**Comment by tiamjiakun** [comment]
<img width="1111" alt="iShot_2024-08-01_11 46 34" src="https://github.com/user-attachments/assets/edfb69be-32aa-43bb-beff-2209b9fb3d6b">

**Comment by gabriel-batistuta** [comment]
Hi tiamjiakun, thanks for the feedback using it. Do you know if you already have pdf2htmlEX installed on your computer? If so, have you configured its path in the environment variables? This library is just a wrapper so it does not work by itself, it depends on pdf2htmlEX.

**Comment by gabriel-batistuta** [comment]
The current pdf2htmlEX doesn't support Windows but you can use the docker image, see here: https://github.com/pdf2htmlEX/pdf2htmlEX/wiki/Download-Docker-Image

**Comment by tiamjiakun** [comment]
OK,thankyou
