### ISSUE TITLE
The file_path parameter in method `to_html` is not effective

### ISSUE THREAD

**Issue by walwel** [gabriel-batistuta/pypdf2htmlEX#4]
`file_path` should be concatenated with `--dest-dir,` not `-o`, `-o` is the shorthand for `--owner-password`.

```python
    def to_html(self, file_path=None):
        if file_path:
            args = ["-o", file_path]
            self.__make_html(args)
        else:
            self.__make_html()
````

You can confirm from here [Command-Line-Options](https://github.com/pdf2htmlEX/pdf2htmlEX/wiki/Command-Line-Options)

**Comment by gabriel-batistuta** [comment]
thanks, you are correct and I corrected it, try now with this new version: https://pypi.org/project/pypdf2htmlex/1.6/
